/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ricde
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarCliente = new javax.swing.JButton();
        lblMenuPrincipal = new javax.swing.JLabel();
        mnbBarraMenu = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuServico = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnCadastrarCliente.setText("Cadastrar Cliente");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarCliente);
        btnCadastrarCliente.setBounds(180, 150, 170, 100);

        lblMenuPrincipal.setDisplayedMnemonic('M');
        lblMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo-MenuPrincipal.jpg"))); // NOI18N
        lblMenuPrincipal.setText("Menu Principal");
        lblMenuPrincipal.setToolTipText("");
        getContentPane().add(lblMenuPrincipal);
        lblMenuPrincipal.setBounds(0, 0, 820, 620);

        mnbBarraMenu.setToolTipText("Menu Principal");
        mnbBarraMenu.setName("Menu Principal"); // NOI18N

        jMenuCadastro.setText("Cadastro");

        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/cliente-icon.png"))); // NOI18N
        jMenuCliente.setText("Cliente");
        jMenuCliente.setToolTipText("");
        jMenuCadastro.add(jMenuCliente);

        jMenuServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/tesoura-icon.png"))); // NOI18N
        jMenuServico.setText("Serviço");
        jMenuCadastro.add(jMenuServico);

        mnbBarraMenu.add(jMenuCadastro);

        jMenu2.setText("Operação");
        mnbBarraMenu.add(jMenu2);

        setJMenuBar(mnbBarraMenu);

        setSize(new java.awt.Dimension(833, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuServico;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JMenuBar mnbBarraMenu;
    // End of variables declaration//GEN-END:variables
}
